datable_django_cartographie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("maps.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "maps"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("display_map", views.display_map, name="display_map"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

maps/models.py
from django.db import models

# Create your models here.

maps/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class TransportationModesForm(forms.Form):
    own_bike_used = forms.BooleanField(
        label="🚲 J’utilise mon vélo (aménagement cyclables + stationnement cyclable)",
        required=False,
    )
    velov_used = forms.BooleanField(
        label="🚲 J’utilise les Vélov’ (aménagement cyclables + stations Vélov’)",
        required=False,
    )
    trains_used = forms.BooleanField(
        label="🚂 Je prends le train (emplacement des gares)",
        required=False,
    )
    cars_used = forms.BooleanField(
        label="🚗 Je prends une voiture (stations autopartages, parkings et parcs relais)",
        required=False,
    )
    taxis_used = forms.BooleanField(
        label="🚕 Je prends le taxi (emplacement des stations de taxis)",
        required=False,
    )
    pmr_used = forms.BooleanField(
        label="👩‍🦽 J’utilise les emplacements de stationnements PMR",
        required=False,
    )
    rhone_buses_used = forms.BooleanField(
        label="🚍 J’utilise les cars du département du Rhône",
        required=False,
    )
    public_transports_used = forms.BooleanField(
        label="🚇 J’utilise les transports en commun TCL (métro, bus, tramway)",
        required=False,
    )
    river_boat_used = forms.BooleanField(
        label="🛥️ J’utilise la navette fluviale (emplacement des stations)",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_id = "id-exampleForm"
        # self.helper.form_class = "blueForms"
        self.helper.form_method = "post"
        self.helper.form_action = "display_map"
        self.helper.add_input(Submit("submit", "Voir ma carte"))

maps/views.py
from django.shortcuts import render
from .gen_maps import gen_maps, MAP_PATH
from django.views.generic import TemplateView
from .forms import TransportationModesForm

# Create your views here.


class IndexView(TemplateView):
    template_name = "maps/index.html"


def display_map(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = TransportationModesForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # retrieve the values from the form
            own_bike_used = form.cleaned_data["own_bike_used"]
            velov_used = form.cleaned_data["velov_used"]
            trains_used = form.cleaned_data["trains_used"]
            cars_used = form.cleaned_data["cars_used"]
            rhone_buses_used = form.cleaned_data["rhone_buses_used"]
            public_transports_used = form.cleaned_data["public_transports_used"]
            taxis_used = form.cleaned_data["taxis_used"]
            river_boat_used = form.cleaned_data["river_boat_used"]
            pmr_used = form.cleaned_data["pmr_used"]

            m = gen_maps(
                own_bike_used=own_bike_used,
                velov_used=velov_used,
                trains_used=trains_used,
                cars_used=cars_used,
                rhone_buses_used=rhone_buses_used,
                public_transports_used=public_transports_used,
                taxis_used=taxis_used,
                river_boat_used=river_boat_used,
                pmr_used=pmr_used,
            )

            # return render(request, "maps/display_map.html", context={'map': m._repr_html_()})
            return render(request, "maps/full_map.html")

    # if a GET (or any other method) we'll create a blank form
    else:
        context = {"form": TransportationModesForm()}
        return render(request, "maps/form_before_map.html", context)

maps/templates/maps/display_map.html
{% extends "base.html" %}

{% block content %}

{{map|safe}}

{% endblock %}

maps/templates/maps/form_before_map.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
<h2>Composition de votre carte de l’intermodalité</h2>

<p>Sélectionnez les offres qui vous concernent pour personnaliser votre carte de chaleur de la Métropole.</p>
<div class="mx-auto">
    <br>
    {% crispy form %}
</div>
{% endblock %}

maps/templates/maps/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1 class="mb-2">Cartographie de l'offre de mobilité de la Métropole de Lyon</h1>


<p>Cette application web vous permet de déterminer les zones de la Métropole offrant le plus d’options de mobilité,
    selon vos préférences.</p>

<h2 class="mt-2 mb-2">1. Sélection des modalités </h2>
<p>La première étape consiste à cocher dans un formulaire les différents modes de déplacement qui vous intéressent.</p>

<img class="img-thumbnail" alt="capture d'écran du formulaire" src="{% static 'maps/form.png' %}" />



<h2 class="mt-2 mb-2">2. Cartographie et interprétation de la carte</h2>

<ol>
    <li>Les données géolocalisant les différentes options choisies sont ensuite téléchargées et projetées sur une carte.
    </li>
    <li>La carte est subdivisée en hexagones de quelques centaines de mètres de diagonale.</li>
    <li>Un score de chaleur est attribué à chaque hexagone selon les offres de mobilité qu’il contient.</li>
    <li>La carte vous est affichée, la couleur de chaque hexagone correspond à son score de chaleur.</li>
</ol>

<img class="img-thumbnail" alt="carte de chaleur" src="{% static 'maps/hex_map.png' %}" />

<a href="{% url 'maps:display_map' %}" class="btn btn-primary mt-3 mb-3">Je compose ma carte</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}Carte Intermodalité Grand Lyon{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🗺️</text></svg>">

</head>

<body>


    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Carte Intermodalité</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'maps:display_map' %}">À la carte</a>
                </li>

                <!--<a class="dropdown-item" href="#">Action</a>-->
            </ul>
        </div>


    </nav>
    <br>

    {% endblock %}
    <div class="container">


        {% block content %}{% endblock %}

    </div>
    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>


    <!-- Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>



</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Home</h1>
{% load static %}

<br><br>


<p>This is definitely the home page.</p>
{% endblock %}